name: Check Lint

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install Modules
      run: npm i
    
    - name: Run Lint
      run: |
        ./node_modules/.bin/eslint persian-calendar@iamrezamousavi.gmail.com
