name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Install Modules
      run: npm i
    
    - name: Run Lint
      run: |
        npx eslint persian-calendar@iamrezamousavi.gmail.com
