name: Continuous Deployment

on:
  push:
    tags:
    - '*'

jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Install Dependencies
        run: |
          sudo apt update -y && \
          sudo apt install -y libglib2.0-bin gettext
      
      - name: Build Project
        run: |
          make zip-file
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Version ${{ github.ref_name }}
          generateReleaseNotes: true
          artifacts: "persian-calendar@iamrezamousavi.gmail.com-v*.zip"
