name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create Zip File
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          path: './persian-calendar@iamrezamousavi.gmail.com/*'
      
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Version ${{ github.ref_name }}
