name: Create Release

on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    name: Create Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Zip File
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: './persian-calendar@iamrezamousavi.gmail.com'
      
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Version ${{ github.ref_name }}
      
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./release.zip
          asset_name: persian-calendar@iamrezamousavi.gmail.com.zip