name: Node.js CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'
    
    - name: Install Modules
      run: npm install
    
    - name: Run Lint
      run: |
        ESLINT_USE_FLAT_CONFIG=false npx eslint persian-calendar@iamrezamousavi.gmail.com

